### PR TITLE
Update to VS2022 and update NuGet key

### PR DESCRIPTION
**Pull request by axunonb**
* use build worker image "Visual Studio 2022"
* update for expiring NuGet API key

### CODE REVIEW

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
Thanks, looks good

**Comment by axunonb** [comment]
@304NotModified Just noticed the nupkg "health" on Appveyor is all red with NugetExplorer?

**Comment by 304NotModified** [comment]
What do you mean? 

Looks all green?
Screenshot_20220317-003834_Brave

**Comment by 304NotModified** [comment]
If its local, just download also the snupkg and save it in the same folder.

**Comment by axunonb** [comment]
> If its local, just download also the snupkg and save it in the same folder.

Wow, exactly! I didn't know that, **thanks a lot**.
(Then NugetExplorer messages about "health" are at least pretty misleading, if the reason is just the missing snupkg.)

**Pull request merged**
