### PR TITLE
ICustomDeserializer never used, but public (breaking change)

### PR DESCRIPTION
**Pull request by axunonb**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Strange it isn't used!

**Comment by axunonb** [comment]
> Strange it isn't used!

Yes, I couldn't believe as well. Sometime the interface would have simplified customer serializers, but it's not that important.

**Comment by 304NotModified** [comment]
Maybe also a good idea to clean the regions?
https://github.com/YAXLib/YAXLib/search?q=ICustomDeserializer&type=

**Review by 304NotModified — APPROVED** [review]
Nice!

**Pull request merged**
