### PR TITLE
Refactor Known Types

### LINKED ISSUE #197: Make Exception a KnownType
Even with a `MaxRecursion` of 10, serializatiion output is too heavy and serialization takes too long.
Add `Exception` to `KnownTypes` with reduced serialization levels and/or members.

### PR DESCRIPTION
**Pull request by axunonb**
Closes #197, #93, #88

In case of #88 a `byte[]` array known type could now be added (instead of using an `ICustomSerializer`

### Known Type related
* All `KnownType<T>.Serialization(...)` and  `KnownType<T>.Deserialization` methods have `SerializationContext` as argument
* Refactor `KnownTypeExtensions`: It's now `XNamespaceExtensions` (`IKnowType` was not used)
* Move classes in folder KnownTypes to namespace `KnownTypes`
* Rename class `KnownTypes` to `WellKnownTypes` and add methods:
  * `Add(...)`
  * `Remove(...)`
  * `Clear()`
  * `RestoreDefault()`
  * `TryGetKnownType(Type? type, out IKnownType? knownType)`
* Add `KnownBaseTypeBase<T>` as another kind of `KnownType<T>`
* Add `ExceptionKnownBaseType` as the first `KnownBaseTypeBase<T>`
* Add `ReflectionUtils.IsBaseClassOrSubclassOf(Type subType, string baseName)` to determine `Exception` subclasses
* Add methods `SetFieldValue` and `SetPropertyValue` to `ReflectionUtils`. They can read/write (also) to private members of base classes. Used for setting the `Exception`'s  private `_message` member.
* Make `IKnownType`, `KnownTypeBase`, `DynamicKnownTypeBase`, `KnownBaseTypeBase` and `WellKnownTypes` **public**
* Add `RecursionCount` as property to `SerializationContext` to keep recursion under control in `IKnownType`s and `ICustomSerializer`s.

### Other
* `YAXSerializationOptions` now have flag "`None = 0`". `SerializeNullObjects` is still the default, and is set in the CTOR of `YAXSerializer`
* `UdtWrapper` CTOR takes `SerializerOptions` as argument, instead of `YAXSerializer`
* `MemberWrapper` CTOR takes `SerializerOptions` as argument, instead of `YAXSerializer`
* `UdtWrapper` and `MemberWrapper` have a property `IKnownType? KnownType` to avoid looking up known types repetitively
* Make abstract `YAXException` CTORs protected
* Increase test coverage for known types, ReflectionUtils, and overall test coverage
* Various code fixed red-flagged by SonarCloud
* Update xmldoc

### CODE REVIEW

**Comment by axunonb** [comment]
See SonarCloud Quality [here](https://sonarcloud.io/summary/new_code?id=axunonb_YAXLib&branch=pr-known-types)

**Comment by 304NotModified** [comment]
This one needs a merge of #199 (and rebase after it) before review

**Comment by axunonb** [comment]
> This one needs a merge of #199 (and rebase after it) before review

Done ;-)

**Comment by axunonb** [comment]
@304NotModified ;-)

**Comment by 304NotModified** [comment]
Sorry, it was too large for me to review. I started it, but it took more time that I had

**Comment by axunonb** [comment]
Yes. I thought so. Feel free to post whenever you stumble across sth. that should be improved, like you did with other PRs. Without this commit it was too difficult to move on, because changes to KnownType and CustomSerializer are closely related. I'll post few questions where I'd like to know your opinion before coding.

**Comment by axunonb** [comment]
Question 1 ;-)
> Make IKnownType, KnownTypeBase, DynamicKnownTypeBase, KnownBaseTypeBase and WellKnownTypes public

This is related to #93. Makes sense this way, or better be more "internal"?

**Comment by 304NotModified** [comment]
Yes that's indeed #93 

I think its a good idea to make them public

**Pull request merged**
