### PR TITLE
Added GitHub Action for SonarCloud integration

### PR DESCRIPTION
**Pull request by axunonb**

### CODE REVIEW

**Comment by axunonb** [comment]
image

**Review by 304NotModified — APPROVED** [review]
Great work :)

**Comment by axunonb** [comment]
@304NotModified SonarCloud integration currently doesn't work: When the account for SonarCloud was created, The "YAXLib" organization and project keys were entered both in lowercase. Also, you're the sole SonarCloud admin. Would you pls change the keys to the same writing as on GitHub (as [described here](https://docs.sonarcloud.io/organizations/overview/#organization-keyscanbe-changed))? I would prefer this instead changing the keys to lowercase in the script.

**Comment by axunonb** [comment]
@304NotModified If you make me a YAXLib SonarCloud admin, I can do it myself ;-)

**Comment by axunonb** [comment]
@304NotModified Fixed with https://github.com/YAXLib/YAXLib/pull/178, using GitHub organization key as lower-case

**Pull request merged**
