### PR TITLE
Remove obsolete packages folder

### PR DESCRIPTION
**Pull request by axunonb**

### CODE REVIEW

**Comment by 304NotModified** [comment]
This needs an interactive rebase :)

Do you need help on that?

**Comment by axunonb** [comment]
Yeah, this proper rebase is my white spot ;-)  Nice you remember

**Comment by 304NotModified** [comment]
White? ;)

Anyway

```
git fetch
git rebase -i origin/master
(Editor opens, remove commits not introduced in the branch)
(Maybe, see text) git rebase --continue
git push --force-with-lease
```

(Typed on mobile, hopefully not typos. Maybe create a backup - by creating a new branch as backup - of course there is also a reflog if things goes wrong)

**Comment by axunonb** [comment]
Thanks for the hint! 
Looking at the new diff, I had expected that only the deleted folder is left (?)
p.s.: This 'white spot' - translated from German ;-) - means somethink blank, uncovered.

**Comment by axunonb** [comment]
Next time I'll do my lessons outside the prod repo.

**Pull request merged**
