### PR TITLE
Remove old .nuget folder

### PR DESCRIPTION
**Pull request by 304NotModified**
This is really not needed anymore

### CODE REVIEW

**Comment by 304NotModified** [comment]
@sinairv could you please give me the permissions to change these repo settings. The AppVeyor connection is still not OK.

**Comment by 304NotModified** [comment]
Please don't merge this one. We need to fix AppVeyor first.

**Comment by axunonb** [comment]
> could you please give me the permissions to change these repo settings.

you're admin now

**Comment by 304NotModified** [comment]
Close/reopen to trigger AppVeyor

**Comment by 304NotModified** [comment]
This one could be merged :)

**Review by axunonb — COMMENTED** [review]
Absolutely: redundant

**Pull request merged**
