### PR TITLE
Added a serialization context when invoking CustomSerializers

### PR DESCRIPTION
**Pull request by bobduncan**
Added functionality for Issue: https://github.com/YAXLib/YAXLib/issues/163
Provides additional information for any custom serializers

### CODE REVIEW

**Comment by 304NotModified** [comment]
This is a breaking change, isn't?

**Comment by axunonb** [comment]
> 
> 
> This is a breaking change, isn't?

Yes, it is (`ICustomSerializer` is changing). `ISerializationContext` would give more power to implementing custom serializers. For sure it required additional documentation, and for now we don't have tests and samples making use of the `ISerializationContext`.
@NKnusperer Your opinion?

**Comment by bobduncan** [comment]
It is indeed a break change and I did not create additional tests or samples for this logic. 
Feel free to disregard this PR if it is inconvenient.

I am not an really an open-source developer so I am not sure how you merge breaking-changes different from non-breaking without forcing an major version bump.

**Comment by 304NotModified** [comment]
Well breaking changes need a major version bump. It's unfortunately that 3.0 is released only a month ago. So a non breaking change is really preferred (e.g. a new interface next to this one).

**Comment by bobduncan** [comment]
It is unlikely that I can change this to a non-breaking change soon. Do you want me to retract this PR?

**Comment by axunonb** [comment]
> 
>It is unlikely that I can change this to a non-breaking change soon. 

To avoid a breaking change, and in case we would consider the change of `ICustomSerializer` for `.NET5.0`+ target frameworks only, could we benefit from the C#8 default interface implementations?

**Comment by 304NotModified** [comment]
I like that idea!

**Comment by axunonb** [comment]
>  does .net standard 2.1 also support default interface implementations

Indeed, [it does](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version).

**Comment by NKnusperer** [comment]
Not sure why we would target `netstandard2.1` instead of directly going with `net5.0`.
The concept of  .NET Standard is dead and new development is exclusively happen on .NET Core.
`netstandard2.1` is also not supported by the full .NET Framework, so this would a platform breaking change anyway.

**Comment by 304NotModified** [comment]
.net 5 will be EOL within a year. 
.net standard 2.1 is also supported by .net core 3.1 - which isn't EOL

**Comment by NKnusperer** [comment]
That why I'm talking about .NET Core instead of  .NET Standard.
Tbh I don't see a reason to switch the target framework anyway, we already have the "catch all" framework eg. `netstandard2.0`.
Changes this just for default interface implementations seems a bit drastic to me.

NET Core 3.1 will  be EOL in 12/2022 and the next LTS release is .NET 6.

**Comment by axunonb** [comment]
> switch the target framework

To be more clear about the proposal:
There would not be a need to move from `NetStandard2.0` to `NetStandard2.1` when using preprocessor directives and C#8 default interface implementations. `NetStandard2.1` would be an additional target framework, where the changed interface had effect, while in `NetStandard2.0` it had not.

**Comment by 304NotModified** [comment]
Yes indeed @axunonb. As I'm not keen on releasing YaxLib 3.0 after a month of XayLib 2.0 😅

**Comment by axunonb** [comment]
### 1. `SerializationContext` implementation

Proving `ICustomSerializer`s with a `SerializationContext` will definitely make custom serializers more powerful. Just wondering, whether changing `ICustomSerializer` is ultimately a must. What if we

* left `ICustomSerializer` as it is
* created a class like `SerializationContextAbstract<T>` implementing `ICustomSerializer<T>`, and having a constructor with `SerializationContext` as the parameter, which is stored and usable with a corresponding property.

=> Custom serializers, that require the `SerializationContext` will derive from `SerializationContextAbstract`, all others stay untouched. We would have to distinguish these cases when creating an instance of the custom serializer.

### 2. `ISerializationContext`

* would be good to add a member for `YAXSerializationOptions`
* should go into a separate file

### 3. Others

* Flag new code files with `#nullable enable`
* Replace `new object[0]` with `Array.Empty<object>()`

What do you think about that?

**Pull request merged**
