### PR TITLE
git(attributes): explicitly normalize line endings

### PR DESCRIPTION
**Pull request by NKnusperer**
This PR solves the problem of line endings not being normalized when doing a checkout under Linux.
This leads to failing tests because inlined expected XML data are using CRLF while the actual data have LF.
- Normalize CRLF/LF line endings within git using `.gitattributes` configuration and `git add --renormalize .`
- Update `.gitignore` from `github/gitignore` and ignore IntelliJ Rider `.idea/` directory.

### CODE REVIEW

**Comment by axunonb** [comment]
Unfortunately we have AppVeyor out of order. Looks like the PR causes 103 tests to fail like this:

Failed CanOverrideAllMetadata [3 ms]
  Error Message:
     Expected string length 371 but was 381. Strings differ at index 112.
  Expected: "..."http://namespace.org/sample">\n  <IntArray yax:dm="2,3">\n ..."
  But was:  "..."http://namespace.org/sample">\r\n  <IntArray yax:dm="2,3">\r..."
  ---------------------------------------------^

**Comment by NKnusperer** [comment]
For me all tests are passing under both Windows and Linux.
I've never used Appveyor, but I guess that maybe something with the checkout settings is wrong.
Is there any particular reason why we are using `msbuild` instead of `dotnet build` in the build definition?

**Comment by NKnusperer** [comment]
@axunonb why did you reverted this change?
Now there are 103 failing tests under Linux again.
As I already said there must be something wrong with the Appveyor settings.
The whole point of this PR is to make the test suite pass under both platform.
Why aren't we fixing the actually problem instead of reverting random stuff?

**Comment by 304NotModified** [comment]
I think it's important that tests succeeds on the ci. I'm also not happy with the merge and revert. 

But at least everything should run on the ci in the pr and if we need to change the AppVeyor settings, then that should be included in that pr.

**Pull request merged**
