### PR TITLE
Add generic constructor

### PR DESCRIPTION
**Pull request by OrbintSoft**
I created a generic class to allow the use of generic constructor

### CODE REVIEW

**Comment by axunonb** [comment]
Thanks for the PR. Makes sense.
@304NotModified What do you think?

**Comment by OrbintSoft** [comment]
I was thinking to make also generic to methods to serialize and deserialize, so we can avoid useless castings. 
But I don't want create breaking changes or create excessive duplications.
Maybe I can create a pull request for v4 , what do you think?

**Comment by 304NotModified** [comment]
> I was thinking to make also generic the methods to serialize and deserialize, so we can avoid useless castings.
> But I don't want create breaking changes or create excessive duplications.
> Maybe I can create a pull request for v4 , what do you think?

I think we need those generic methods before this has really an benefit. But I have to agree, that's more work then expected. Nevertheless, it could be without breaking changes (if we don't merge this one).

I really like a generic class, but with generic methods (serialize , deserialize)

**Review by 304NotModified — CHANGES_REQUESTED** [review]
Without generic methods. It will be a breaking change if we add them.

**Comment by OrbintSoft** [comment]
I have added generic methods, there are no breaking changes, but I have to hide base implementation with **new** keyword.

**Comment by axunonb** [comment]
@304NotModified Suggest to rename `YAXSerializer.generic.cs` to more common `YAXSerializerOfT.cs` or ```YAXSerializer`1.cs``` and then merge.

**Pull request merged**
